quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=1234
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/emp_curd?useSSL=false&serverTimezone=UTC

quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
quarkus.http.port=8082

# Employee Service
quarkus.rest-client.employee-api.url=http://localhost:8081

# Swagger
quarkus.smallrye-openapi.path=/swagger

# Logging
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n